### ISSUE TITLE
Makefile recipe for target install-js failed

### ISSUE THREAD

**Issue by DeastinY** [arecker/bennedetto#14]
Hi, please see error attached:

> python manage.py migrate
> Operations to perform:
>   Synchronize unmigrated apps: flat, staticfiles, messages, debug_toolbar, compressor, rest_framework
>   Apply all migrations: tracking, sessions, admin, auth, contenttypes, authenticating
> Synchronizing apps without migrations:
>   Creating tables...
>     Running deferred SQL...
>   Installing custom SQL...
> Running migrations:
>   No migrations to apply.
> npm install
> make: npm: Command not found
> Makefile:9: recipe for target 'install-js' failed
> make: **\* [install-js] Error 127

**Comment by DeastinY** [comment]
After installing npm with

> sudo apt-get install npm
> I get 
> info it worked if it ends with ok
> verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'install' ]
> info using npm@1.1.4
> info using node@v0.6.19
> verbose config file /home/pi/.npmrc
> verbose config file /usr/etc/npmrc
> verbose config file /usr/share/npm/npmrc
> ERR! Couldn't read dependencies.
> ERR! Error: 'version' field missing
> ERR! 'version' Must be X.Y.Z, with an optional trailing tag.
> ERR! See the section on 'version' in `npm help json`
> ERR!     at /usr/share/npm/lib/utils/read-json.js:368:13
> ERR!     at /usr/share/npm/lib/utils/read-json.js:166:33
> ERR!     at P (/usr/share/npm/lib/utils/read-json.js:142:41)
> ERR!     at /usr/share/npm/lib/utils/read-json.js:108:7
> ERR!     at [object Object].<anonymous> (fs.js:123:5)
> ERR!     at [object Object].emit (events.js:64:17)
> ERR!     at fs.js:1190:12
> ERR!     at Object.oncomplete (/usr/lib/nodejs/graceful-fs.js:94:5)
> ERR! You may report this log at:
> ERR!     http://bugs.debian.org/npm
> ERR! or use
> ERR!     reportbug --attach /home/pi/bennedetto/npm-debug.log npm
> ERR! 
> ERR! System Linux 4.1.7-v7+
> ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
> ERR! cwd /home/pi/bennedetto
> ERR! node -v v0.6.19
> ERR! npm -v 1.1.4
> ERR! message 'version' field missing
> ERR! message 'version' Must be X.Y.Z, with an optional trailing tag.
> ERR! message See the section on 'version' in `npm help json`
> verbose exit [ 1, true ]

**Comment by arecker** [comment]
Interesting.  I didn't realize the `version` was required in the `package.json`.  I've had no issues.

Can you try again after installing `nodejs-legacy`

```
$ sudo apt-get install nodejs-legacy
```

**Comment by shindakun** [comment]
v0.6.19 and v1.1.4 are pretty old as far as node and npm releases go.

**Comment by arecker** [comment]
Oh thanks, @shindakun I just noticed that.  I'm on npm 2.7.4.  It looks like you are just going to have to upgrade, @DeastinY

**Comment by DeastinY** [comment]
Upgraded npm to version 3.1.4 with 

> sudo npm install -g npm
> (Somehow had to run it twice, before it took effect).
> Furthermore I installed nodejs-legacy,

Another issue I stumbled upon was grunt, that was missing.
All in all installation was a big hassle. Not sure if it's you're fault though :)

**Comment by arecker** [comment]
Haha - glad it worked out for you.  Sorry you had issues.

**Comment by DeastinY** [comment]
thank's for the fast support, just wait a few seconds, already opening a new case :smile:
