### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by DeastinY** [arecker/bennedetto#15]
Hi @arecker,
just got the project up and running, up to the point where it says:

> Starting development server at http://127.0.0.1:8000/

As I have the server running bennedetto in my local network I'd like to connect to it now, but it's not reachable under IP-ADRESS:8000.
Is there maybe some flag I have to set, before I can connect via network ?

Kind regards,
keep up the great work !

**Comment by arecker** [comment]
You can just manually run python manage.py runserver 0.0.0.0:8000 if you
need to access it from another machine. That should bind it publicly

**Comment by DeastinY** [comment]
k, thanks, bye - worked lika a charm :)

**Comment by arecker** [comment]
Sweet.  I take it you're running it from a raspberry pi.  Sounds cool.
