### ISSUE TITLE
Test coverage for authenticating

### ISSUE THREAD

**Issue by arecker** [arecker/bennedetto#3]
While most of it is pretty boilerplate, we could still probably benefit from some tests coverage for
- `authenticating.forms.UserCreationForm`, namely the need for passwords to match
- `authenticating.models.UserManager`, namely the difference between `create_user` and `create_superuser`.  That's an important distinction

**Comment by arecker** [comment]
We don't need an enormous test suite right away.  It would be cool if someone creating a `authenticating/tests.py` with a few `SimpleTestCase` suites to exercise the custom user model and form.

Maybe a `Makefile` entry so you can call the tests with 

```
$ make test
```

**Comment by emersion** [comment]
Fixed by #30
