### ISSUE TITLE
Docker: could not determine git version

### ISSUE THREAD

**Issue by arecker** [arecker/bennedetto#32]
See #25 

Edit: apparently, this is just a warning message that prints when you stop the server.  It still runs, but it would be create if we could suppress this.

**Comment by DoomHammer** [comment]
Yes, I got it too, but does it hurt in any way?

**Comment by arecker** [comment]
So you can still run it? It's just a warning?

**Comment by DoomHammer** [comment]
I believe so. It only happens when I close the container not when I start it. Also: what Django uses Git for?

**Comment by arecker** [comment]
Ah - I thought it was totally broken.  If it's more of a weird warning, then I wouldn't be too worried about it.  I'll leave the issue open in case anyone figures out a way to suppress it.

**Comment by DoomHammer** [comment]
The question remains: why Django moans about it? Have you got any idea where it may be coming from?

This way we could understand what is going on and what to do with it :)

**Comment by arecker** [comment]
`¯\_(ツ)_/¯`

**Comment by DoomHammer** [comment]
We're in this together.

**Comment by arecker** [comment]
Oh man.  This is kind of embarrassing.  Now I know why I can't find anything with that error message.

_I_ wrote the error message : ) https://github.com/arecker/bennedetto/blob/master/bennedetto/settings/common.py#L86

The idea is that as the app is starting up, it grabs the output of `git describe` and just gives up if it can't.  Removing the try/except in `settings.common` will show you the error.

**Comment by DoomHammer** [comment]
Don't worry. We all have days like that.

I believe something like [GitPython](http://gitpython.readthedocs.org/en/stable/) might be a slightly better approach.

This will fail miserably still if there is no `.git` around (eg. release from tarball, remote deploy, etc.). Maybe better stick with a [ChangeLog](http://keepachangelog.com/) and parse it?

**Comment by arecker** [comment]
I like the idea of a parsed ChangeLog.  It seems coupling it so closely with git really limits deployment options.

Do you want to take that?  I've never set one of these up, but you were nice enough to provide the documentation so I can if you'd like.

**Comment by DoomHammer** [comment]
Sure. As soon as I have a bit of time to spare I'll try to hack something up.

**Comment by arecker** [comment]
Awesome.  Thanks Piotr.

**Comment by DoomHammer** [comment]
Imagine a situation that CHANGELOG.md contains:

```
## Unreleased
### Added
- bar

## 0.1 - 2015-11-20
### Added
- foo
```

We are running Unreleased code. What do we want `VERSION` to be set to?
1. `Unreleased`
2. `0.1`
3. `0.1-Unreleased`
4. Choose your own adventure

**Comment by arecker** [comment]
How exciting.

I think I like 3.  How can it tell what version we are running?

**Comment by DoomHammer** [comment]
How about
1. Read line of `CHANGELOG.md`.
2. If it matches `/^## Unreleased$/` set `unreleased` to `True`.
3. If if matches `/^## ([0-9]+)/` set `base_version` to `m.group(1)` and exit the loop.
4. Read next line.

?

**Comment by arecker** [comment]
That seems totally reasonable.  Once you set VERSION, the middleware
will pick it up and you will be able to view it in the navbar.

**Comment by DoomHammer** [comment]
I hope I will write some robust parser in the near future as it might benefit my other needs, but for now keeping it simple should suffice.

**Comment by arecker** [comment]
I agree.
And at some point, it would be kind of cool to get it into a `TemplateView` so we could link to the changelog from the app.  Something to think about....

**Comment by shindakun** [comment]
Just throwing this out there, have not looked to deeply into it (python is not my strong suit) but changing the Dockerfile from `FROM django` to `FROM django:1.8.6-python2` seems to resolve the the message as well.  ;)

**Comment by arecker** [comment]
Interesting.  We've already narrowed it down to the `VERSION` code in `settings.common`.  Maybe that bit of code isn't python3 compatible?

In any case, it's kind of a moot point because we'll be setting the version number without git.

**Comment by DoomHammer** [comment]
Here you go: #37

**Comment by arecker** [comment]
I'm guessing this is fixed now
