### ISSUE TITLE
Better +/- UX for forms

### ISSUE THREAD

**Issue by arecker** [arecker/bennedetto#47]
Right now the app relies on just typing a `-` into the number input.  It would be great if there was a friendlier way to render that.

Along with an additional widget, there will probably need to be some logic in the serializer to negate the value _if_ (something) when creating and updating.

**Comment by arecker** [comment]
Now that I think of it, a [material switch](https://material.angularjs.org/latest/demo/switch) would probably look really sharp here.

Defaults switched 'on' for negative, tap to switch positive.  That would be really easy to drop in there too.

**Comment by cachitas** [comment]
I also noticed that writing the minus sign there was not very user friendly. 
I like the switch idea to change between income and outcome.

**Comment by arecker** [comment]
That sounds really doable.  I should be able to get that in soon.  Probably won't even need to touch the serializer, which doesn't sound like that great of an idea now.  The API itself should just take a number.
