### ISSUE TITLE
Split grunt tasks into build and test

### ISSUE THREAD

**Issue by arecker** [arecker/bennedetto#51]
The grunt tasks, which now run all together, should be split for usefulness.
- `grunt build`: browserify, cssmin, copy, replace (and pretty much anything that just _builds_ source)
- `grunt test`: jshint, jasmine, and anything having to do with code quality
-  `grunt`: everything

**Comment by DoomHammer** [comment]
Or go with `npm` like [this](http://blog.keithcirkel.co.uk/why-we-should-stop-using-grunt/)?

**Comment by arecker** [comment]
This is interesting.  I definitely like it.  Indeed, grunt does get a
little bloated.

I would love to try this out eventually for the sake up thinning npm
dependencies.

For know, it's easiest to just make another grunt command, but I would
like to eventually come back around to try it with straight npm.

**Comment by DoomHammer** [comment]
Like this: #55?

**Comment by arecker** [comment]
That's the one. Thanks

If you want to start playing around with npm run [script], you are more
than welcome.
