### ISSUE TITLE
Django 1.9 Upgrade

### ISSUE THREAD

**Issue by arecker** [arecker/bennedetto#57]
I would like to think about switching to Django 1.9 while we are still in greenfield development

I'm expecting to find a few issues, so anyone who can install django 1.9 and get it running with no errors or warnings will be my hero.

**Comment by cachitas** [comment]
After upgrading Django in my virtualenv to 1.9 and running `manage.py migrate`, I got the following deprecation warnings:
-  `RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.`
- `RemovedInDjango110Warning: 'get_all_related_objects is an unofficial API that has been deprecated. You may be able to replace it with 'get_fields()'`
- `RemovedInDjango110Warning: 'get_all_related_many_to_many_objects is an unofficial API that has been deprecated. You may be able to replace it with 'get_fields()'`

Hope this helps!

**Comment by DoomHammer** [comment]
Psst, children, wanna buy some Django? Try #58 .

**Comment by arecker** [comment]
Thanks for this, Hugo.  I'm assuming all the tests still passed?

It's nice to see that the only cost of upgrading is just a few
warnings.  And judging by the ones you provided, it sounds like those
are coming from plugins and I trust those will take care of themselves.

I'll probably sit on Django 1.8 until DRF updates.

**Comment by arecker** [comment]
Lol @DoomHammer - always trying to push the newer shiny things on kids, eh?

I merged in #58, so the docker image will be on 1.9.  That can kind of act as a canary in the coal mine for now.

If things work out, I'll update `requirements/dev.txt` and close the issue

**Comment by cachitas** [comment]
Yes all tests passed. And only the first warning I mentioned previously was raised during the tests. The others were by playing around with the app.

**Comment by arecker** [comment]
Sweet.  Screw it - let's just upgrade.

@cachitas want to get a commit in there?  We just need to add 1.9 to tox and update requirements/dev.txt

This is tox.ini

```
-envlist = py27-django{18}, py34-django{18}
+envlist = py27-django{18,19}, py34-django{18,19}
...
 deps =
-    django18: Django>=1.8, <1.9
```

We can remove that line in `deps =` too, since it's not doing anything.  Tox knows where to get `django18` and `django19`.

**Comment by DoomHammer** [comment]
Tested my change more extensively and found out it doesn't work as advertised. It installs 1.9 alright, but then uses the one provided by `requirements/*.txt`. After proper upgrade I have deprecation warnings as noted. During building it is:

```
/usr/local/lib/python3.4/site-packages/django/db/models/fields/subclassing.py:22: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  RemovedInDjango110Warning)
```

**Comment by arecker** [comment]
That's fine.  Actually now that I think about it we should probably just upgrade the whole project with `dev.txt` and `prod.txt` together.

**Comment by DoomHammer** [comment]
Great. Once you build your container with current master, it's 1.9.0 all the way down.

**Comment by arecker** [comment]
Sweet deal.  I'd like to leave older versions of django on tox.ini for
as long as possible.  At least until they become a real pain to support.
