### ISSUE TITLE
Move jasmine to devDependencies

### ISSUE THREAD

**Issue by emersion** [arecker/bennedetto#60]
`jasmine` is only needed for tests, normal users don't have to install it. Is it possible to move `grunt-contrib-jasmine` to `devDependencies`?

**Comment by arecker** [comment]
This is a good point.  Actually most npm dependencies would fall in that category.  I was going to commit a "build" of the vendor scripts so some wouldn't even need to deal with grunt at all.

I'll leave this issue open to remind me to get on that.

**Comment by arecker** [comment]
I decided to just make npm stuff optional for _all_ contributors/hackers.

I've committed a 'rollup' of vendor.js, vendor.min.css, and the fonts.  That way, if you have no interest messing around with the clientside code, you can totally avoid installing node.

I've removed some cruft form the makefile and updated the README.

@DoomHammer I just tested out the Dockerfile and things are still working (as it should, it's still doing it the old way).  Feel free to remove all the nodejs silliness from the Dockerfile for the sake of brevity.

Instead, the burden of rebuilding the static resources will lie on whoever is modifying them.

**Comment by DoomHammer** [comment]
As soon as I find some spare time (how does that even sound?), I will :)
