### ISSUE TITLE
Add ability to add another user through the UI

### ISSUE THREAD

**Issue by joelbrewer** [arecker/bennedetto#63]
Currently no way to add users through the user interface (as far as I am aware). Would be nice to have a form for adding additional users.

**Comment by arecker** [comment]
Have you tried the register link from the homepage?  You should be able to create a user there.

**Comment by joelbrewer** [comment]
Ah. Must have missed that! I'll try in the morning. Does that mean anyone with the url to my app can sign up and see my data though? Is there any concept of an "admin" ?

**Comment by arecker** [comment]
There is.  Only superusers (or users with `staff = True`) can access the django admin.  Regular users can only see their data at the homepage.

Object level permissions are enforced with the `@restrict_to_user` decorator.
