### ISSUE TITLE
logo not showing

### ISSUE THREAD

**Issue by rainforest1155** [arecker/bennedetto#70]
Looks like the logo filename may not match what's in the code as the logo doesn't show. The console says this:
[17/Feb/2016 01:40:18] "GET /static/images/bennedetto.png HTTP/1.1" 404 1675

but looking at the actual folder, the image name is:
Bennedetto.png

Changing the filename to bennedetto.png fixes this for me.

**Comment by arecker** [comment]
Was this the development server?

Regardless, we should definitely change the file or path.  PR welcome if you want to get in the changelog for an easy fix!

**Comment by rainforest1155** [comment]
I cloned the Master repository and followed the instructions from the "Building" section. I guess that's what you mean by development server?
My first pull request is here #72!
