### ISSUE TITLE
unicode character in transaction / rate description causing admin tracking page to load

### ISSUE THREAD

**Issue by rainforest1155** [arecker/bennedetto#76]
I have an umlaut (ü) in one of my transactions and while that's working fine in the main UI, it causes the admin/tracking/transaction page to fail:
`
UnicodeEncodeError at /admin/tracking/transaction/
'ascii' codec can't encode character u'\xfc' in position 1: ordinal not in range(128)
Request Method: GET
Request URL:    http://localhost:8080/admin/tracking/transaction/
Django Version: 1.9
Exception Type: UnicodeEncodeError
Exception Value:  
'ascii' codec can't encode character u'\xfc' in position 1: ordinal not in range(128)
Exception Location: /home/cortezkin/git/bennedetto/tracking/models.py in **unicode**, line 130
Python Executable:  /home/cortezkin/.virtualenvs/bennedetto/bin/python
Python Version: 2.7.3
Python Path:  
['/home/user/git/bennedetto',
 '/home/user/.virtualenvs/bennedetto/lib/python2.7',
 '/home/user/.virtualenvs/bennedetto/lib/python2.7/plat-linux2',
 '/home/user/.virtualenvs/bennedetto/lib/python2.7/lib-tk',
 '/home/user/.virtualenvs/bennedetto/lib/python2.7/lib-old',
 '/home/user/.virtualenvs/bennedetto/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-linux2',
 '/usr/lib/python2.7/lib-tk',
 '/home/user/.virtualenvs/bennedetto/local/lib/python2.7/site-packages']
Server time:    Wed, 17 Feb 2016 22:22:59 +0100
Unicode error hint

The string that could not be encoded/decoded was: Lüttge
Error during template rendering

In template /home/user/.virtualenvs/bennedetto/local/lib/python2.7/site-packages/django/contrib/admin/templates/admin/change_list.html, error at line 91
ascii
81          {% endif %}
82        {% endblock %}
83  
84        <form id="changelist-form" method="post"{% if cl.formset.is_multipart %} enctype="multipart/form-data"{% endif %} novalidate>{% csrf_token %}
85        {% if cl.formset %}
86          <div>{{ cl.formset.management_form }}</div>
87        {% endif %}
88  
89        {% block result_list %}
90            {% if action_form and actions_on_top and cl.show_admin_actions %}{% admin_actions %}{% endif %}
91            {% result_list cl %}
92            {% if action_form and actions_on_bottom and cl.show_admin_actions %}{% admin_actions %}{% endif %}
93        {% endblock %}
94        {% block pagination %}{% pagination cl %}{% endblock %}
95        </form>
96      </div>
97    </div>
98  {% endblock %}
99  
`
The same also happens for the admin/tracking/rates page.

**Comment by arecker** [comment]
I'm suspecting the `__unicode__` function for that model.  Up for grabs!

**Comment by arecker** [comment]
Fixed.  My `__unicode__` functions were returning `str`'s.
